---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    template:
      data:
        # OAUTH
        ENABLE_OAUTH_SIGNUP: "true"
        ENABLE_OAUTH_PERSISTENT_CONFIG: "false"
        OAUTH_MERGE_ACCOUNTS_BY_EMAIL: "true"
        OAUTH_PROVIDER_NAME: Authentik
        OPENID_PROVIDER_URL: https://sso.${SECRET_DOMAIN}/application/o/open-web-ui/.well-known/openid-configuration
        OAUTH_SCOPES: openid email profile
        OPENID_REDIRECT_URI: https://chat.${SECRET_DOMAIN}/oauth/oidc/callback
        OAUTH_CLIENT_ID: "{{ .OPEN_WEBUI_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPEN_WEBUI_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{ .OPEN_WEBUI_POSTGRES_DB }"
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .OPEN_WEBUI_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .OPEN_WEBUI_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Database
        DATABASE_URL: postgres://{{ .OPEN_WEBUI_POSTGRES_USER }}:{{ .OPEN_WEBUI_POSTGRES_PASSWORD }}@postgres17-rw.database.svc.cluster.local/{{ .OPEN_WEBUI_POSTGRES_DB }}
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: open-webui