exclude:
  platforms:
  - _info.txt
  - '@eaDir'
  - video
  - .Stfolder
  - images
  - videos
  - '*.Stfolder'
  - '*.txt'
  - '*syncthing*'
  - '*:Zone.Identifier'
  roms:
    multi_file:
      names:
      - _hidden
      - images
      - '@eaDir'
      - '!images'
      - '!orphaned'
      - '!downloading'
      - txt
      - manuals
      - cfg
      - stignore
      - '*videos'
      - '*manuals'
      - .Stfolder
      - '*syncthing*'
      - '*:Zone.Identifier'
      parts:
        extensions:
        - txt
        - xml
        - jpg
        - jpeg
        - images
        - cfg
        - stignore
        - '*videos'
        - .Stfolder
        - '*syncthing*'
        - syncthing
        - '*:Zone.Identifier'
        names:
        - data.xml
        - ._*
        - multidisc
        - manuals
        - cfg
        - '*manuals'
        - syncthing
        - '*syncthing*'
        - '*:Zone.Identifier'
    single_file:
      extensions:
      - xml
      - txt
      - jpg
      - jpeg
      - pdf
      - images
      - manuals
      - '*.cfg'
      - stignore
      - '*.Stfolder'
      - '*syncthing*'
      - syncthing
      - '*:Zone.Identifier'
      names:
      - info.txt
      - ._*
      - '*.nfo'
      - '@eaDir'
      - '*.xml'
      - '!info.txt'
      - mp4
      - '*.mp4'
      - '*.cfg'
      - cfg
      - stignore
      - '*manuals'
      - '*.Stfolder'
      - syncthing
      - '*:Zone.Identifier'
filesystem: { }
system:
  platforms:
    bbc: bbcmicro
    dreamcast: dc
    gamecube: ngc
    gamegear: gamegear
    gb: gb
    gba: gba
    gbc: gbc
    lynx: lynx
    mame: arcade
    megadrive: genesis-slash-megadrive
    n64: n64
    neogeo: neogeoaes
    nes: nes
    pcengine: turbografx16--1
    ps2: ps2
    ps3: ps3
    psp: psp
    psx: ps
    saturn: saturn
    sega32x: sega-32x
    segacd: segacd
    snes: snes
    switch: switch
    wii: wii
    wiiu: wiiu
    wswan: wonderswan
    wswanc: wonderswan-color
    xbox: xbox
    zxspectrum: zxs
  versions: {}