---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app aska
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    controllers:
      aska:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: struppinet/aska-dedicated-server
              tag: latest@sha256:ec4b0f4c5381377c89a31d42452fa89f8e1949dd74cc499d787e73bb0b77941c
            env:
              TZ: ${TIMEZONE}
              AUTOSAVE_STYLE: "every 20 minutes"
              KEEP_WORLD_ALIVE: false
              SAVE_ID: e9819_010226191257
              SERVER_PORT: &gameport 27015
              SERVER_QUERY_PORT: &queryport 27016
              # Server Properties
              ASKA_SEED: LosAngeles
              ASKA_MODE: custom
              ASKA_TERRAIN_ASPECT: smooth # smooth, normal, rocky
              ASKA_TERRAIN_HEIGHT: flat # flat, normal, varied
              ASKA_STARTING_SEASON: spring
              ASKA_YEAR_LENGTH: default
              ASKA_PRECIPITATION: 3
              ASKA_DAY_LENGTH: default
              ASKA_STRUCTURE_DECAY: low
              ASKA_CLOTHING_DECAY: low
              ASKA_INVASION_DIFICULTY: hard # off, easy, normal, hard - they mispelled difficulty, check on this later
              ASKA_MONSTER_DENSITY: medium
              ASKA_MONSTER_POPULATION: medium
              ASKA_WULFAR_POPULATION: high
              ASKA_HERBIVORE_POPULATION: high
              ASKA_BEAR_POPULATION: high
            envFrom:
              - secretRef:
                  name: aska-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: false
            resources:
              requests:
                cpu: 1000m
                memory: 9Gi
              limits:
                memory: 14Gi
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.10.40.147
        ports:
          gameport:
            enabled: true
            port: *gameport
            protocol: UDP
          queryport:
            enabled: true
            port: *queryport
            protocol: UDP

    persistence:
      data:
        enabled: true
        existingClaim: *app
        advancedMounts:
          aska:
            app:
              - path: /home/container/.wine/drive_c/users/container/AppData/LocalLow/Sand Sailor Studio/Aska/data/server
                subPath: savegame
              - path: /home/container/server_files
                subPath: server