---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

metrics: true

ui:
  title: Infrastructure Status
  header: Status
  logo: https://avatars.githubusercontent.com/u/33636445
  link: https://github.com/gtw2
  buttons:
    - name: Github
      link: https://github.com/gtw2
    - name: Homelab
      link: https://github.com/gtw2/home-ops

web:
  port: ${GATUS_WEB_PORT}