---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: games
components:
  - ../../components/common
resources:
  - ./aska/ks.yaml
  - ./enshrouded/ks.yaml
  - ./factorio/ks.yaml
  - ./icarus/ks.yaml
  - ./minecraft/ks.yaml
  - ./romm/ks.yaml
  # - ./sdtd/ks.yaml
  # - ./starrupture/ks.yaml
  - ./valheim/ks.yaml
